# Generated by Django 3.1.2 on 2020-11-11 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ONSALE', 'SELL'), ('ONRENT', 'RENT')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('FURNISHED HOME', 'FURNISHED HOME'), ('LAND AND PLOT', 'LAND & PLOT'), ('RENTAL', 'RENTAL')], max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('bathrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('built_up_area', models.FloatField()),
                ('carpet_area', models.FloatField()),
                ('unit', models.CharField(choices=[('yards', 'yards'), ('cents', 'cents'), ('acres', 'acres')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('Resale', 'Resale'), ('new', 'New Booking')], max_length=50)),
                ('property_floor', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('ownership', models.CharField(choices=[('Individual', 'Individual'), ('Joint', 'Joint')], max_length=200)),
                ('total_floors', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('availability', models.CharField(choices=[('ready', 'Ready to move'), ('construction', 'Under construction')], max_length=200)),
                ('description', models.TextField(blank=True)),
                ('posting_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
