# Generated by Django 3.1.2 on 2020-10-28 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('built_up_area', models.FloatField()),
                ('carpet_area', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('property_floor', models.CharField(max_length=200)),
                ('ownership', models.CharField(max_length=200)),
                ('total_floors', models.IntegerField()),
                ('availability', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('posting_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
