# Generated by Django 3.1.2 on 2020-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='action_type',
            field=models.CharField(choices=[('ONSALE', 'SELL'), ('ONRENT', 'RENT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.CharField(choices=[('ready', 'Ready to move'), ('construction', 'Under construction')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ownership',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Joint', 'Joint')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(choices=[('10000', '10000'), ('20000', '20000'), ('30000', '30000'), ('40000', '40000'), ('50000', '50000'), ('60000', '60000'), ('70000', '70000'), ('80000', '80000'), ('90000', '90000'), ('100000', '100000'), ('200000', '200000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_floor',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('FURNISHED HOME', 'FURNISHED HOME'), ('LAND AND PLOT', 'LAND & PLOT'), ('RENTAL', 'RENTAL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='total_floors',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transaction_type',
            field=models.CharField(choices=[('Resale', 'Resale'), ('new', 'New Booking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='unit',
            field=models.CharField(choices=[('yards', 'yards'), ('cents', 'cents'), ('acres', 'acres')], max_length=50),
        ),
    ]
