# Generated by Django 3.1.2 on 2020-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201028_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_floor',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
    ]
