# Generated by Django 3.1.2 on 2020-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlist', '0002_shortlist_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='slot',
            field=models.CharField(choices=[('FORENOON', 'FORENOON'), ('AFTERNOON', 'AFTERNOON')], max_length=50),
        ),
    ]
