# Generated by Django 3.1.2 on 2020-11-11 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_user', models.ImageField(default='photos/2020/10/30/avatar.jpeg', upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(default='sdsdsadsdasdasdasdsadasdsad', max_length=200)),
                ('phone', models.CharField(default='838848484', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
