# Generated by Django 3.1.2 on 2020-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_user',
            field=models.ImageField(default='photos/2020/10/30/avatar.jpeg', upload_to='user/propics'),
        ),
    ]
