# Generated by Django 3.1.2 on 2020-11-24 15:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201111_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_user',
            field=django_resized.forms.ResizedImageField(crop=None, default='photos/2020/10/30/avatar.jpeg', force_format=None, keep_meta=True, quality=75, size=[600, 600], upload_to='photos/user/propic'),
        ),
    ]
