# Generated by Django 3.1.2 on 2020-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201127_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='7839939939', max_length=200),
        ),
    ]
