# Generated by Django 3.1.2 on 2020-10-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
