# Generated by Django 3.1.2 on 2020-11-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='first_name',
            field=models.CharField(default='Adam', max_length=200),
        ),
        migrations.AddField(
            model_name='realtor',
            name='last_name',
            field=models.CharField(default='John', max_length=200),
        ),
        migrations.AddField(
            model_name='realtor',
            name='username',
            field=models.CharField(default='adj111', max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
