# Generated by Django 3.1.2 on 2020-11-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20201106_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/home-1.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
