# Generated by Django 3.1.2 on 2020-11-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20201108_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, default='https://realbuy-bucket.s3.amazonaws.com/photos/2020/10/28/gate_image.jpg?AWSAccessKeyId=AKIAVJB47BNVETDCWWP6&Signature=MrV%2F0n5UPw1t50tW82J8V9Z4STM%3D&Expires=1604827184', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
