# Generated by Django 3.1.2 on 2020-11-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20201108_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, default='photos/2020/10/28/gate_image.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
